CREATE TABLE CATEGORIES (
category_id INTEGER IDENTITY(1,1) NOT NULL,
label VARCHAR(30) NOT NULL
)

ALTER TABLE CATEGORIES ADD CONSTRAINT category_pk PRIMARY KEY (category_id)

CREATE TABLE USERS (
user_id INTEGER IDENTITY(1,1) NOT NULL,
username VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
first_name VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL,
phone VARCHAR(15),
street VARCHAR(30) NOT NULL,
postal_code VARCHAR(10) NOT NULL,
city VARCHAR(50) NOT NULL,
password VARCHAR(30) NOT NULL,
credit INTEGER NOT NULL,
administrator bit NOT NULL
)

ALTER TABLE USERS ADD CONSTRAINT user_pk PRIMARY KEY (user_id)

CREATE TABLE SOLD_ITEMS (
item_id INTEGER IDENTITY(1,1) NOT NULL,
item_name VARCHAR(30) NOT NULL,
description VARCHAR(300) NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL,
initial_price INTEGER,
sale_price INTEGER,
user_id INTEGER NOT NULL,
category_id INTEGER NOT NULL
)

ALTER TABLE SOLD_ITEMS ADD CONSTRAINT sold_items_pk PRIMARY KEY (item_id)

CREATE TABLE WITHDRAWALS (
item_id INTEGER NOT NULL,
street VARCHAR(30) NOT NULL,
postal_code VARCHAR(15) NOT NULL,
city VARCHAR(30) NOT NULL
)

ALTER TABLE WITHDRAWALS ADD CONSTRAINT withdrawal_pk PRIMARY KEY (item_id)

ALTER TABLE WITHDRAWALS
ADD CONSTRAINT withdrawal_item_fk FOREIGN KEY (item_id) REFERENCES SOLD_ITEMS (item_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION

CREATE TABLE BIDS (
bid_id INTEGER IDENTITY(1,1) NOT NULL,
bid_date DATETIME NOT NULL,
bid_amount INTEGER NOT NULL,
item_id INTEGER NOT NULL,
user_id INTEGER NOT NULL
)

ALTER TABLE BIDS ADD CONSTRAINT bid_pk PRIMARY KEY (bid_id)

ALTER TABLE BIDS
ADD CONSTRAINT bid_user_fk FOREIGN KEY (user_id) REFERENCES USERS (user_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE BIDS
ADD CONSTRAINT bid_item_fk FOREIGN KEY (item_id) REFERENCES SOLD_ITEMS (item_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE SOLD_ITEMS
ADD CONSTRAINT sold_items_category_fk FOREIGN KEY (category_id) REFERENCES CATEGORIES (category_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE SOLD_ITEMS
ADD CONSTRAINT sold_items_user_fk FOREIGN KEY (user_id) REFERENCES USERS (user_id)
ON DELETE NO ACTION
ON UPDATE NO ACTION